#!/bin/sh

#synapseid="syn7502921"
synapseid="syn7821845"
dockerurl="docker.synapse.org"

preprocessname="simple-preprocess"
preprocessimage="${dockerurl}/${synapseid}/${preprocessname}"

trainname="vgg16"
trainimage="${dockerurl}/${synapseid}/${trainname}"

scorename="keras-score"
scoreimage="${dockerurl}/${synapseid}/${scorename}"
