#!/bin/sh

synapseid="syn7502921"
dockerurl="docker.synapse.org"

preprocessname="mik2015-simple-preprocess"
preprocessimage="${dockerurl}/${synapseid}/${preprocessname}"

trainname="mik2015-simple-cnn-vgg16"
trainimage="${dockerurl}/${synapseid}/${trainname}"

